document.addEventListener("DOMContentLoaded", async () => {
  const descriptionField = document.getElementById('description');
  if (descriptionField) descriptionField.textContent = 'Code generated by /quote';

  // #region 1. Data Loading
  // Fetch all necessary JSON data files in parallel for efficiency.
  // These files contain mappings for item IDs, reprocessing values, multipliers, and group information.
  const [
    typeMapRaw, 
    reprocessingMap, 
    reprocessables, 
    multiplierMap, 
    typeGroupsRaw, 
    groupIdsRaw
  ] = await Promise.all([
    fetch('jsons/type_ids.json').then(r => r.json()),
    fetch('jsons/reprocessing_map.json').then(r => r.json()),
    fetch('jsons/reprocessables.json').then(r => r.json()),
    fetch('jsons/multipliers.json').then(r => r.json()),
    fetch('jsons/type_groups.json').then(r => r.ok ? r.json() : {}).catch(() => ({})),
    fetch('jsons/group_ids.json').then(r => r.ok ? r.json() : {}).catch(() => ({}))
  ]);
  // #endregion

  // #region 2. Map Construction
  // Process the raw data into more usable map formats for quick lookups.
  const typeMap = {};
  const idToNameMap = {};
  for (const [name, id] of Object.entries(typeMapRaw)) {
    typeMap[name.toLowerCase()] = id;
    idToNameMap[id] = name;
  }
  window.typeMapForContracts = idToNameMap;

  // Invert Group Map (ID -> Name) for lookup
  const groupIDToName = {};
  for (const [name, id] of Object.entries(groupIdsRaw)) groupIDToName[id] = name; 
  // #endregion

  // #region 3. Multiplier Resolution Logic
  /**
   * DEPRECATED: This function had an incorrect priority order.
   * It checked for group multipliers before item-specific ones.
   * It is kept for historical reference but is superseded by `resolveMultiplierCorrected`.
   */
  function resolveMultiplier(typeID) {
    if (!multiplierMap) return 0.93;

    // Helper: Case-insensitive lookup
    const check = (key) => {
        if (!key) return null;
        if (multiplierMap[key] !== undefined) return parseFloat(multiplierMap[key]);
        if (typeof key === 'string') {
            const lower = key.toLowerCase();
            const found = Object.keys(multiplierMap).find(k => k.toLowerCase() === lower);
            if (found) return parseFloat(multiplierMap[found]);
        }
        return null;
    };

    let val = null;

    // Step 1: CHECK GROUP (Higher Priority for general rules)
    const gid = typeGroupsRaw[String(typeID)];
    if (gid) {
        // A. Group Name (e.g. "Mineral")
        const gName = groupIDToName[gid];
        if (gName && (val = check(gName)) !== null) return val;
        
        // B. Group Key (e.g. "group:18")
        if ((val = check(`group:${gid}`)) !== null) return val;
        
        // C. Group ID (e.g. "18")
        if ((val = check(String(gid))) !== null) return val;
    }

    // Step 2: CHECK ITEM (Specific overrides)
    // We check item last so specific items can override groups if needed? 
    // Actually, usually specific overrides general. Let's check Item FIRST.
    // (Swapping order to standard: Specific > General)
    
    // A. Item ID (e.g. "34")
    if ((val = check(typeID)) !== null) return val;
    if ((val = check(String(typeID))) !== null) return val;
    
    // B. Item Name (e.g. "Tritanium")
    const iName = idToNameMap[typeID];
    if (iName && (val = check(iName)) !== null) return val;

    return 0.93; // Default
  }

  /**
   * Resolves the correct buyback multiplier for a given type ID.
   * The logic follows a specific-to-general priority:
   * 1. Item ID (most specific)
   * 2. Item Name
   * 3. Group Name, Group Key (e.g., "group:18"), or Group ID (most general)
   * @param {number|string} typeID - The EVE Online type ID of the item.
   * @returns {number} The resolved multiplier, or a default of 0.93 if none is found.
   */
  function resolveMultiplierCorrected(typeID) {
      if (!multiplierMap) return 0.93;
      const check = (key) => {
          if (!key) return null;
          if (multiplierMap[key] !== undefined) return parseFloat(multiplierMap[key]);
          if (typeof key === 'string') {
              const f = Object.keys(multiplierMap).find(k => k.toLowerCase() === key.toLowerCase());
              if (f) return parseFloat(multiplierMap[f]);
          }
          return null;
      };

      let val;
      // 1. Specific Item Override
      if ((val = check(typeID)) !== null) return val;
      if ((val = check(String(typeID))) !== null) return val;
      const iName = idToNameMap[typeID];
      if (iName && (val = check(iName)) !== null) return val;

      // 2. Group Fallback
      const gid = typeGroupsRaw[String(typeID)];
      if (gid) {
          const gName = groupIDToName[gid];
          if (gName && (val = check(gName)) !== null) return val;
          if ((val = check(`group:${gid}`)) !== null) return val;
          if ((val = check(String(gid))) !== null) return val;
      }
      return 0.93;
  }
  // #endregion

  // #region 4. Main Calculation Logic
  // Attach the primary calculation logic to the "Calculate" button's click event.
  const calculateBtn = document.getElementById("calculate");
  if (!calculateBtn) return;

  calculateBtn.addEventListener("click", async () => {
    // Get user input and DOM elements for displaying results.
    const rawText = document.getElementById("item-list").value.trim();
    const modalItems = document.getElementById("modal-items");
    const modalTotal = document.getElementById("modal-total");
    const location = document.getElementById("location").value;

    // Clear previous results.
    modalItems.innerHTML = "";
    modalTotal.innerHTML = "";
    let total = 0;

    /**
     * Parses a single line of text from the input to extract an item name and quantity.
     * Handles various formats like "Item Name x5", "Item Name (5)", and "Item Name 5".
     * @param {string} line - A single line from the item list textarea.
     * @returns {object|null} An object with `name` and `qty` properties, or null if the line is empty.
     */
    function parseLine(line) {
        line = line.trim();
        if (!line) return null;
        let m = line.match(/^(.*?)(?:\s*)\((?:x)?\s*([\d,]+)\)\s*$/i) || 
                line.match(/^(.*\S)\s+[xX]\s*([\d,]+)\s*$/);
        if (m) return { name: m[1].trim(), qty: parseInt(m[2].replace(/,/g, ''), 10) || 1 };
        if (typeMap[line.toLowerCase()]) return { name: line, qty: 1 };
        m = line.match(/^(.*\S)\s+([\d,]+)\s*$/);
        if (m) {
             const name = m[1].trim();
             if (typeMap[name.toLowerCase()]) 
                 return { name: name, qty: parseInt(m[2].replace(/,/g, ''), 10) || 1 };
        }
        return { name: line, qty: 1 };
    }

    // Process each line from the input.
    const lines = rawText.split("\n");
    const pricedItems = [];
    const materialTotals = {};
    let reprocessedValue = 0;

    // First pass: Identify items, separate reprocessables, and aggregate materials.
    for (const line of lines) {
        const parsed = parseLine(line);
        if (!parsed) continue;

        const typeID = typeMap[parsed.name.toLowerCase()];
        if (!typeID) {
            modalItems.innerHTML += `<p style="color:red;">${parsed.name} not recognized</p>`;
            continue;
        }

        // Check if the item is marked as reprocessable.
        const isRepro = Object.keys(reprocessables).find(k => k.toLowerCase() === parsed.name.toLowerCase());
        if (isRepro) {
             const materials = reprocessingMap[typeID];
             if (materials) {
                 modalItems.innerHTML += `<p><s>${parsed.name} × ${parsed.qty.toLocaleString()}</s></p>`;
                 for (const [matID, matQty] of Object.entries(materials)) {
                     const totalMat = Math.floor(matQty * parsed.qty * 0.9063);
                     materialTotals[matID] = (materialTotals[matID] || 0) + totalMat;
                 }
             }
        } else {
             pricedItems.push({ ...parsed, typeID });
        }
    }

    // Compile a list of all unique type IDs that need pricing from the market.
    const allIDs = [...new Set([...pricedItems.map(i => i.typeID), ...Object.keys(materialTotals)])];
    let priceMap = {};
    if (allIDs.length > 0) {
        try {
            const res = await fetch(`/api/market_prices/?type_ids=${allIDs.join(',')}`);
            const data = await res.json();
            priceMap = data.prices || {};
        } catch (e) { console.error("Price fetch failed", e); }
    }

    // Second pass: Calculate the value of standard (non-reprocessed) items.
    for (const item of pricedItems) {
        const pInfo = priceMap[item.typeID];
        const basePrice = pInfo?.price || 0;
        const mult = resolveMultiplierCorrected(item.typeID);
        const finalPrice = basePrice * mult;
        const lineTotal = finalPrice * item.qty;
        total += lineTotal;

        modalItems.innerHTML += `
        <div class="quote-row" style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
            <img class="quote-icons" src="https://images.evetech.net/types/${item.typeID}/icon">
            <div>${item.name}</div>
            <div>${item.qty.toLocaleString()}</div>
            <div>@ ${finalPrice.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
            <div>${lineTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
            <div>${(mult*100).toFixed(1)}%</div>
        </div>`;
    }

    // Third pass: Calculate the value of the aggregated reprocessed materials.
    if (Object.keys(materialTotals).length > 0) {
        modalItems.innerHTML += `<p><strong>Reprocessed Materials:</strong></p>`;
        for (const [matID, qty] of Object.entries(materialTotals)) {
            const pInfo = priceMap[matID];
            const basePrice = pInfo?.price || 0;
            const mult = resolveMultiplierCorrected(matID);
            const finalPrice = basePrice * mult;
            const lineTotal = finalPrice * qty;
            reprocessedValue += lineTotal;
            total += lineTotal;
            
            const matName = idToNameMap[matID] || matID;
            modalItems.innerHTML += `
            <div class="quote-row" style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
                <img class="quote-icons" src="https://images.evetech.net/types/${matID}/icon">
                <div>${matName}</div>
                <div>${qty.toLocaleString()}</div>
                <div>@ ${finalPrice.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
                <div>${lineTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
                <div>${(mult*100).toFixed(1)}%</div>
            </div>`;
        }
    }

    // Apply hauling fee if the location is not a primary hub.
    if (!location) { alert("Select location!"); return; }
    if (location !== "UALX-3" && location !== "ABE-M2") {
        total -= 50000000;
        modalItems.innerHTML += `<p style="color:orange;">-50,000,000 ISK Hauling Fee</p>`;
    }

    // Display the final total and show the result box.
    modalTotal.innerHTML += `<h3>Total: ${total.toLocaleString(undefined,{minimumFractionDigits:2})} ISK</h3>`;
    document.getElementById("result-box").style.display = "block";
    
    // Send the raw item list to the backend to generate and store a unique quote code.
    fetch('/api/quotes/', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(rawText)})
      .then(r=>r.json()).then(d => { if(d.code) descriptionField.textContent = d.code; });
  });

  // Attach click handlers for the copy buttons.
  document.getElementById("copyBtn").onclick = () => navigator.clipboard.writeText(document.getElementById("modal-total").innerText.replace(/[^\d.]/g,''));
  document.getElementById("copyCodeBtn").onclick = () => navigator.clipboard.writeText(descriptionField.textContent);
});