document.addEventListener("DOMContentLoaded", async () => {
  const descriptionField = document.getElementById('description');
  if (descriptionField) descriptionField.textContent = 'Code generated by /quote';

  // #region 1. Data Loading
  // Fetch multipliers and reprocessables configurations.
  const [
    reprocessables, 
    multiplierMap
  ] = await Promise.all([
    fetch('jsons/reprocessables.json').then(r => r.json()),
    fetch('jsons/multipliers.json').then(r => r.json())
  ]);
  
  // Dynamically update the default rate display on index.html if present
  const defaultRateSpan = document.getElementById('default-rate');
  if (defaultRateSpan && multiplierMap && multiplierMap['_default'] !== undefined) {
    const defaultPct = (parseFloat(multiplierMap['_default']) * 100).toFixed(1).replace(/\.0$/, '');
    defaultRateSpan.textContent = `${defaultPct}%`;
  }
  // #endregion

  // #region 2. State Variables
  // These will be populated dynamically from the backend during calculation.
  let typeMap = {};
  let idToNameMap = {};
  let typeGroupsRaw = {};
  let reprocessingMap = {};
  let reprocessingPortionMap = {};
  let groupIDToName = {};
  // #endregion

  // #region 3. Multiplier Resolution Logic
  /**
   * DEPRECATED: This function had an incorrect priority order.
   * It checked for group multipliers before item-specific ones.
   * It is kept for historical reference but is superseded by `resolveMultiplierCorrected`.
   */
  function resolveMultiplier(typeID) {
    if (!multiplierMap) return 0.93;
    const defaultMult = multiplierMap['_default'] !== undefined ? parseFloat(multiplierMap['_default']) : 0.93;

    // Helper: Case-insensitive lookup
    const check = (key) => {
        if (!key) return null;
        if (multiplierMap[key] !== undefined) return parseFloat(multiplierMap[key]);
        if (typeof key === 'string') {
            const lower = key.toLowerCase();
            const found = Object.keys(multiplierMap).find(k => k.toLowerCase() === lower);
            if (found) return parseFloat(multiplierMap[found]);
        }
        return null;
    };

    let val = null;

    // Step 1: CHECK GROUP (Higher Priority for general rules)
    const gid = typeGroupsRaw[String(typeID)];
    if (gid) {
        // A. Group Name (e.g. "Mineral")
        const gName = groupIDToName[gid];
        if (gName && (val = check(gName)) !== null) return val;
        
        // B. Group Key (e.g. "group:18")
        if ((val = check(`group:${gid}`)) !== null) return val;
        
        // C. Group ID (e.g. "18")
        if ((val = check(String(gid))) !== null) return val;
    }

    // Step 2: CHECK ITEM (Specific overrides)
    // We check item last so specific items can override groups if needed? 
    // Actually, usually specific overrides general. Let's check Item FIRST.
    // (Swapping order to standard: Specific > General)
    
    // A. Item ID (e.g. "34")
    if ((val = check(typeID)) !== null) return val;
    if ((val = check(String(typeID))) !== null) return val;
    
    // B. Item Name (e.g. "Tritanium")
    const iName = idToNameMap[typeID];
    if (iName && (val = check(iName)) !== null) return val;

    return defaultMult; // Default
  }

  /**
   * Resolves the correct buyback multiplier for a given type ID.
   * The logic follows a specific-to-general priority:
   * 1. Item ID (most specific)
   * 2. Item Name
   * 3. Group Name, Group Key (e.g., "group:18"), or Group ID (most general)
   * @param {number|string} typeID - The EVE Online type ID of the item.
   * @returns {number} The resolved multiplier, or a default of 0.93 if none is found.
   */
  function resolveMultiplierCorrected(typeID) {
      if (!multiplierMap) return 0.93;
      const defaultMult = multiplierMap['_default'] !== undefined ? parseFloat(multiplierMap['_default']) : 0.93;
      const check = (key) => {
          if (!key) return null;
          if (multiplierMap[key] !== undefined) return parseFloat(multiplierMap[key]);
          if (typeof key === 'string') {
              const f = Object.keys(multiplierMap).find(k => k.toLowerCase() === key.toLowerCase());
              if (f) return parseFloat(multiplierMap[f]);
          }
          return null;
      };

      let val;
      // 1. Specific Item Override
      if ((val = check(typeID)) !== null) return val;
      if ((val = check(String(typeID))) !== null) return val;
      const iName = idToNameMap[typeID];
      if (iName && (val = check(iName)) !== null) return val;

      // 2. Group Fallback
      const gid = typeGroupsRaw[String(typeID)];
      if (gid) {
          const gName = groupIDToName[gid];
          if (gName && (val = check(gName)) !== null) return val;
          if ((val = check(`group:${gid}`)) !== null) return val;
          if ((val = check(String(gid))) !== null) return val;
      }
      return defaultMult;
  }
  // #endregion

  // #region 4. Main Calculation Logic
  // Attach the primary calculation logic to the "Calculate" button's click event.
  const calculateBtn = document.getElementById("calculate");
  if (!calculateBtn) return;

  calculateBtn.addEventListener("click", async () => {
    // Get user input and DOM elements for displaying results.
    const rawText = document.getElementById("item-list").value.trim();
    if (!rawText) {
      alert("Please paste items into the text area before getting a quote.");
      return;
    }

    const modalItems = document.getElementById("modal-items");
    const modalTotal = document.getElementById("modal-total");
    const locationSelect = document.getElementById("location");
    const location = locationSelect ? locationSelect.value : "";

    if (!location) {
      alert("Please select a location from the dropdown menu first.");
      return;
    }

    // Clear previous results.
    modalItems.innerHTML = "";
    modalTotal.innerHTML = "";
    let total = 0;

    function parseLine(line) {
        line = line.trim();
        if (!line) return null;
        let m = line.match(/^(.*?)(?:\s*)\((?:x)?\s*([\d,]+)\)\s*$/i) || 
                line.match(/^(.*\S)\s+[xX]\s*([\d,]+)\s*$/) ||
                line.match(/^(.*\S)\s+([\d,]+)\s*$/);
        if (m) return { name: m[1].trim(), qty: parseInt(m[2].replace(/,/g, ''), 10) || 1 };
        return { name: line, qty: 1 };
    }

    // Process each line from the input.
    const lines = rawText.split("\n");
    const parsedLines = [];
    
    for (const line of lines) {
        const parsed = parseLine(line);
        if (parsed) parsedLines.push(parsed);
    }
    
    // Resolve items via API
    const namesToResolve = [...new Set(parsedLines.map(p => p.name))];
    if (namesToResolve.length > 0) {
        try {
            const resolveRes = await fetch('/api/sde/resolve_items', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({ names: namesToResolve })
            });
            const resolvedItems = await resolveRes.json();
            
            for (const item of resolvedItems) {
                typeMap[item.name.toLowerCase()] = item.id;
                idToNameMap[item.id] = item.name;
                typeGroupsRaw[item.id] = item.group_id;
                reprocessingPortionMap[item.id] = item.portion_size || 100;
                
                if (Object.keys(item.reprocessing).length > 0) {
                    const matObj = {};
                    for (let matId in item.reprocessing) {
                        matObj[matId] = item.reprocessing[matId].quantity;
                        idToNameMap[matId] = item.reprocessing[matId].name;
                        typeGroupsRaw[matId] = item.reprocessing[matId].group_id;
                    }
                    reprocessingMap[item.id] = matObj;
                }
            }
        } catch (e) {
            console.error("Failed to resolve items:", e);
        }
    }
    window.typeMapForContracts = idToNameMap;

    const pricedItems = [];
    const materialTotals = {};
    let reprocessedValue = 0;

    // First pass: Identify items, separate reprocessables, and aggregate materials.
    for (const parsed of parsedLines) {

        const typeID = typeMap[parsed.name.toLowerCase()];
        if (!typeID) {
            modalItems.innerHTML += `<p style="color:red;">${parsed.name} not recognized</p>`;
            continue;
        }

        // Check if the item is marked as reprocessable.
        const isRepro = Object.keys(reprocessables).find(k => k.toLowerCase() === parsed.name.toLowerCase());
        if (isRepro) {
             const materials = reprocessingMap[typeID];
             if (materials) {
                 const portion = reprocessingPortionMap[typeID] || 100;
                 modalItems.innerHTML += `<p><s>${parsed.name} × ${parsed.qty.toLocaleString()}</s></p>`;
                 for (const [matID, matQty] of Object.entries(materials)) {
                     const totalMat = Math.floor(matQty * (parsed.qty / portion) * 0.9063);
                     materialTotals[matID] = (materialTotals[matID] || 0) + totalMat;
                 }
             }
        } else {
             pricedItems.push({ ...parsed, typeID });
        }
    }

    // Compile a list of all unique type IDs that need pricing from the market.
    const allIDs = [...new Set([...pricedItems.map(i => i.typeID), ...Object.keys(materialTotals)])];
    let priceMap = {};
    if (allIDs.length > 0) {
        try {
            const res = await fetch('/api/market_prices/', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ type_ids: allIDs })
            });
            const data = await res.json();
            priceMap = data.prices || {};
        } catch (e) { console.error("Price fetch failed", e); }
    }

    // Second pass: Calculate the value of standard (non-reprocessed) items.
    for (const item of pricedItems) {
        const pInfo = priceMap[item.typeID];
        const basePrice = pInfo?.price || 0;
        const mult = resolveMultiplierCorrected(item.typeID);
        const finalPrice = basePrice * mult;
        const lineTotal = finalPrice * item.qty;
        total += lineTotal;

        modalItems.innerHTML += `
        <div class="quote-row" style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
            <img class="quote-icons" src="https://images.evetech.net/types/${item.typeID}/icon">
            <div>${item.name}</div>
            <div>${item.qty.toLocaleString()}</div>
            <div>@ ${finalPrice.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
            <div>${lineTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
            <div>${(mult*100).toFixed(1)}%</div>
        </div>`;
    }

    // Third pass: Calculate the value of the aggregated reprocessed materials.
    if (Object.keys(materialTotals).length > 0) {
        modalItems.innerHTML += `<p><strong>Reprocessed Materials:</strong></p>`;
        for (const [matID, qty] of Object.entries(materialTotals)) {
            const pInfo = priceMap[matID];
            const basePrice = pInfo?.price || 0;
            const mult = resolveMultiplierCorrected(matID);
            const finalPrice = basePrice * mult;
            const lineTotal = finalPrice * qty;
            reprocessedValue += lineTotal;
            total += lineTotal;
            
            const matName = idToNameMap[matID] || matID;
            modalItems.innerHTML += `
            <div class="quote-row" style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
                <img class="quote-icons" src="https://images.evetech.net/types/${matID}/icon">
                <div>${matName}</div>
                <div>${qty.toLocaleString()}</div>
                <div>@ ${finalPrice.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
                <div>${lineTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
                <div>${(mult*100).toFixed(1)}%</div>
            </div>`;
        }
    }

    // Apply hauling fee if location has fee attached
    const selectedOption = locationSelect && locationSelect.selectedIndex >= 0 ? locationSelect.options[locationSelect.selectedIndex] : null;
    const haulingFee = selectedOption ? parseFloat(selectedOption.getAttribute('data-fee') || '0') : 0;
    if (haulingFee > 0) {
        total -= haulingFee;
        modalItems.innerHTML += `<p style="color:orange;">-${haulingFee.toLocaleString()} ISK Hauling Fee</p>`;
    }

    // Display the final total and show the result box.
    modalTotal.innerHTML += `<h3>Total: ${total.toLocaleString(undefined,{minimumFractionDigits:2})} ISK</h3>`;
    const resultBox = document.getElementById("result-box");
    if (resultBox) resultBox.style.display = "block";
    
    // Send the raw item list to the backend to generate and store a unique quote code.
    fetch('/api/quotes/', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(rawText)})
      .then(r=>r.json()).then(d => { if(d && d.code && descriptionField) descriptionField.textContent = d.code; });
  });

  // Attach click handlers for the copy buttons if present.
  const copyBtn = document.getElementById("copyBtn");
  if (copyBtn) {
    copyBtn.onclick = () => navigator.clipboard.writeText(document.getElementById("modal-total").innerText.replace(/[^\d.]/g,''));
  }
  const copyCodeBtn = document.getElementById("copyCodeBtn");
  if (copyCodeBtn) {
    copyCodeBtn.onclick = () => navigator.clipboard.writeText(descriptionField ? descriptionField.textContent : '');
  }
});